### ISSUE TITLE
server-nodejs crash

### ISSUE THREAD

**Issue by remyla** [remyla/damas-core#166]
when performing this read:

$ damas read tests/test4

GET /api/verify/ 200 2.679 ms - 216
[ '/tests/test4' ]

/home/primcode/bin/damas-core/server-nodejs/node_modules/mongodb/lib/utils.js:99
    process.nextTick(function() { throw err; });
                                        ^
TypeError: Cannot read property 'length' of undefined
    at /home/primcode/bin/damas-core/server-nodejs/db/mongodb.js:117:51
    at Array.reduce (native)
    at /home/primcode/bin/damas-core/server-nodejs/db/mongodb.js:115:39
    at handleCallback (/home/primcode/bin/damas-core/server-nodejs/node_modules/mongodb/lib/utils.js:96:56)
    at /home/primcode/bin/damas-core/server-nodejs/node_modules/mongodb/lib/cursor.js:853:16
    at handleCallback (/home/primcode/bin/damas-core/server-nodejs/node_modules/mongodb/node_modules/mongodb-core/lib/cursor.js:172:5)
    at setCursorDeadAndNotified (/home/primcode/bin/damas-core/server-nodejs/node_modules/mongodb/node_modules/mongodb-core/lib/cursor.js:507:3)
    at nextFunction (/home/primcode/bin/damas-core/server-nodejs/node_modules/mongodb/node_modules/mongodb-core/lib/cursor.js:655:7)
    at Cursor.next [as _next] (/home/primcode/bin/damas-core/server-nodejs/node_modules/mongodb/node_modules/mongodb-core/lib/cursor.js:696:3)
    at fetchDocs (/home/primcode/bin/damas-core/server-nodejs/node_modules/mongodb/lib/cursor.js:849:10)

**Comment by remyla** [comment]
Here is the debug result:

"/tests/test4" is exactly 12 bytes and for some reasons mongoDB ObjectID.isValid("/tests/test4") returns true.

Here are some discussions about this issue:

https://github.com/Automattic/mongoose/issues/1959
http://stackoverflow.com/questions/11985228/mongodb-node-check-if-objectid-is-valid

replacing
-        if (ObjectID.isValid(id)) {

with this (testing if it is exactly a 24 hex)
+        if (/^[a-fA-F0-9]{24}$/.test(id) && ObjectID.isValid(id)) {
fixes the issue
