### ISSUE TITLE
server-nodejs, when ES6 not ready

### ISSUE THREAD

**Issue by remyla** [remyla/damas-core#195]
Some Ecmascript 2015 (ES6) arrived in our permissions.js code.

This could be a problem when running the code on NodeJS v0.10.29, which is the version natively found on Debian 8 Jessie (the current stable Debian version) which is the supported distribution for damas-core/server-nodejs . We would like the core to stick compatible with ES5 until next stable version of Debian. However, some optional extensions could explicitly need Node version >4 without problem.

```js
TypeError: Object function Array() { [native code] } has no method 'from'
    at /home/primcode/bin/damas-core-experimental/server-nodejs/routes/permissions.js:10:29
    at Layer.handle [as handle_request] (/home/primcode/bin/damas-core-experimental/server-nodejs/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/home/primcode/bin/damas-core-experimental/server-nodejs/node_modules/express/lib/router/index.js:312:13)
    at /home/primcode/bin/damas-core-experimental/server-nodejs/node_modules/express/lib/router/index.js:280:7
    at param (/home/primcode/bin/damas-core-experimental/server-nodejs/node_modules/express/lib/router/index.js:349:14)
    at param (/home/primcode/bin/damas-core-experimental/server-nodejs/node_modules/express/lib/router/index.js:365:14)
    at Function.process_params (/home/primcode/bin/damas-core-experimental/server-nodejs/node_modules/express/lib/router/index.js:410:3)
    at next (/home/primcode/bin/damas-core-experimental/server-nodejs/node_modules/express/lib/router/index.js:271:10)
    at /home/primcode/bin/damas-core-experimental/server-nodejs/routes/index.js:23:9
    at Layer.handle [as handle_request] (/home/primcode/bin/damas-core-experimental/server-nodejs/node_modules/express/lib/router/layer.js:95:5)
```

**Comment by remyla** [comment]
The proposed solution is contained in commit ecb93d345b8511015859dd51733ef34fc3b29195

We added an extension `server-nodejs/extensions/es6_polyfills.js` in order to provide missing ES6 to older NodeJS. Closing issue
